### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by voron56** [ia-stepanov/autosend-letters-hh#3]

**Comment by ia-stepanov** [comment]
Здравствуйте! Вы указали, что программа не работает, но не предоставили дополнительную информацию. Можете, пожалуйста, описать проблему подробнее, указать шаги для воспроизведения ошибки или предоставить скриншоты?

**Comment by ia-stepanov** [comment]
Автор не предоставил дополнительной информации. Не могу воспроизвести проблему, поэтому закрываю это issue. Если у вас возникнут новые вопросы или проблемы, пожалуйста, не стесняйтесь открыть новое issue с подробным описанием.
